
server:
  port: 8081

#spring:
#  profiles:
#    active: dev

#spring:
#  profiles:
#    active: prod
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hotel_room_management_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      idle-timeout: 180000
      auto-commit: true
      minimum-idle: 5

mybatis:
  configuration:
    map-underscore-to-camel-case: true


---
server:
  port: 8082
spring:
  profiles: dev
---
spring:
  profiles: prod

